version: 2
jobs:
  build_test_xenial:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install dependencies
          command: apt update && apt-get -y install build-essential git sudo wget cmake
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake . && make
      - run: export GTEST_COLOR=1 && ctest -VV
  build:
    docker:
      - image: zondax/builder_bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/ledger

workflows:
  version: 2
  build_all:
    jobs:
      - build_test_xenial
      - build
